#!/usr/bin/with-contenv bash

FLAGS=""

if ! [ -e /dev/net/tun ]; then
    FLAGS="$FLAGS --tun=userspace-networking"
    if [ -v TAILSCALE_USE_EXIT_NODE ]; then
        FLAGS="$FLAGS  --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055"
    fi
fi

if [ -v TAILSCALE_STATE_DIR ]; then
    FLAGS="$FLAGS --statedir=${TAILSCALE_STATE_DIR}"
else
    echo '[!] TAILSCALE_STATE_DIR is not set, this node will be ephemeral.'
    FLAGS="$FLAGS --state=mem:"
fi

if ! [ -v TAILSCALE_TAILSCALED_LOG ]; then
    sudo tailscaled $FLAGS 2>&1 > /dev/null
else
    sudo tailscaled $FLAGS
fi
